### PR TITLE
Convert recaptcha to h-captcha

### PR DESCRIPTION
**Pull request by cheslin23**
h-captcha is more secure than recaptcha, also changed readme.md as you requested :)

I emailed you the secret you need to add to your config file.

### CODE REVIEW

**Comment by cheslin23** [comment]
This also contains the email validator, run this: `pip install email-validator` or `pip3 install email-validator`

**Review by cheslin23 — COMMENTED** [review]
Making sure code contained email validator

**Review by cheslin23 — COMMENTED** [review]
Moving the `from email_validator import validate_email, EmailNotValidError` to the top as like you said, is a bad practice

**Review by dheslin24 — APPROVED** [review]
lgtm

**Pull request merged**
